### ISSUE TITLE
An Error Was Encountered Hatası

### ISSUE THREAD

**Issue by melihozdemir** [mdxyz/dizilab#11]
Merhaba, Unable to load the requested file: helpers/my_helper.php böyle bir hata alıyorum acaba sebebi nedir ne yapmalıyım? Kurmak için ?

**Comment by melihozdemir** [comment]
Herşeyi hallettim ama css dosyalarını çekmiyor bide 403 hatası veriyor onu nasıl yapacağım ?

**Comment by mdxyz** [comment]
Helper hatasının sizden kaynaklı(host ve local sunucunuz) sorun olduğunu düşünüyorum. my_helper dosyasında css dosyalarını çekmek yardımcı bir fonksiyon var. Hatayı gidermek amaçlı helper dosyasıyla oynama yapmanız sonucu böyle bir sorun ortaya çıkmış olabilir.

**Comment by melihozdemir** [comment]
Sizle nasıl iletişim kurabilirim ? Özel olarak konuşarak iş talebi vermek istiyorum.

**Comment by mdxyz** [comment]
mail ile olabilir, magicslip@gmail.com
