### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by kyuza** [mdxyz/dizilab#5]
Merhabalar,

local de kurmaya çalıştığım zaman aşağıda ki linkte ki gibi bir problem ortaya çıkmaktadır.

İyi çalışmalar,

http://prntscr.com/9mfa49

**Comment by mdxyz** [comment]
Merhaba! php.ini dosyasından short_open_tag'i açarsanız hiçbir sorun kalmaz.

**Comment by kyuza** [comment]
Tekrardan kontrol sağladım on konumunda.Fakat problem halen aynı şekilde devam ediyor.

**Comment by kyuza** [comment]
Sorun çözüldü teşekkürler :)

**Comment by kyuza** [comment]
Tekrardan merhabalar, admin paneline erişim sağlayamıyorum, bu konu da yardımcı olabilirmisiniz ?

**Comment by mdxyz** [comment]
Yönetici Paneli henüz kodlanmadı. Takipte kalın

**Comment by kyuza** [comment]
Tamamdır,bir sorum daha olacak.Kendi sunucum da kurmaya çalıştığım da 404 hatası veriyor.  .htaccess dosyasını düzenlememe rağmen.

**Comment by mdxyz** [comment]
Websitenizde mi kurdunuz?

**Comment by kyuza** [comment]
Evet.

**Comment by mdxyz** [comment]
app/config/config.php dosyasını düzenlediniz mi?

**Comment by kyuza** [comment]
Evet base url kısmını değiştirdim.

**Comment by mdxyz** [comment]
htaccess dosyasını tekrar indirip dener misiniz?

**Comment by kyuza** [comment]
problem halen aynı.

**Comment by mdxyz** [comment]
sunucuda htaccess kullanımı aktif mi?

**Comment by kyuza** [comment]
Evet aktif.

**Comment by mdxyz** [comment]
Link atar mısınız? Göz atalım.

**Comment by kyuza** [comment]
http://zenenet.esy.es/

**Comment by kyuza** [comment]
Birde local de üye girişi yapamıyorum aynı şekil de kayıt işlemi de sayfa için de takılıp kalıyor.

**Comment by mdxyz** [comment]
CodeIgniter 2.x sistem dosyalarını kullanarak deneyin.

**Comment by erenroma** [comment]
Merhaba dosyaları sunucuya yükledim. Gereken yerleri düzenledim. kyuza "http://zenenet.esy.es/" arkadaşın dediği aynı sorun bendede var. 404 çıkıyor anasayfada.

**Comment by mdxyz** [comment]
dizilab'i tekrar indirip deneyin.

**Comment by kyuza** [comment]
Buyrun; <?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed'); ?>

ERROR - 2016-01-23 13:35:49 --> Severity: Warning  --> include(/home/u539998075/public_html/app/errors/error_general.php): failed to open stream: No such file or directory /home/u539998075/public_html/system/core/Exceptions.php 147
ERROR - 2016-01-23 13:35:49 --> Severity: Warning  --> include(): Failed opening '/home/u539998075/public_html/app/errors/error_general.php' for inclusion (include_path='.:/opt/php-5.5/pear') /home/u539998075/public_html/system/core/Exceptions.php 147

**Comment by mdxyz** [comment]
app\logs klasöründeki hatayı yapıştırın. 
![untitledhata](https://cloud.githubusercontent.com/assets/12167194/12530445/3e827b14-c1e8-11e5-9b6b-5a4636efe5aa.png)

**Comment by kyuza** [comment]
Yukarı da yapıştırdığım hatalar zaten ''log-2016-01-23.php'' dosyasının içinde ki hatalar.

**Comment by mdxyz** [comment]
Hatayı aldığınız tarihteki dosyanın içeriğini yapıştırın. Ayrıca sistemi ücretsiz hosting sitesinde kullanıyorsanız çalışmıyor olabilir.
![image](https://cloud.githubusercontent.com/assets/12167194/12530449/64575882-c1e8-11e5-8683-2526fa9e18a0.png)

**Comment by mdxyz** [comment]
Sistemi xampp ile kendi bilgisayarınıza kurmayı deneyin. Sorunsuz çalışacaktır.

**Comment by kyuza** [comment]
doğru local de bir sorun yok zaten,ben sadece sunucu üzerinde bir denemek istemiştim.

**Comment by mdxyz** [comment]
Çıktıya göre sunucuda kurulu olan php versiyonu 5.5 onu 5.6 ya yükseltin.

**Comment by kyuza** [comment]
Şimdi de şöyle bir hata veriyor.Log dosyasını bu sefer oluşturmuyor.

Parse error: syntax error, unexpected 've' (T_STRING) in /home/kyuza/public_html/app/config/config.php on line 33

**Comment by mdxyz** [comment]
app/config/config.php dosyasındaki 33. satırı yapıştırın

**Comment by kyuza** [comment]
| Typically this will be your index.php file, unless you've renamed it to

**Comment by mdxyz** [comment]
config.php dosyasını tekrar indirip deneyin. Herhangi bir sorunla karşılaşırsanız internette araştırın.
