### ISSUE TITLE
veritabanı sorunu

### ISSUE THREAD

**Issue by mertgonul** [mdxyz/dizilab#8]
sql dosyasında eksik tablolar var, Table 'db615256518.forumlar' doesn't exist gibi bir hata alıyorum. tekrar bir sql yedeği yükleyebilirseniz sevinirim.

**Comment by mdxyz** [comment]
Buyrun

`SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for `forumlar`
-- ----------------------------
DROP TABLE IF EXISTS `forumlar`;
CREATE TABLE `forumlar` (
  `id` int(33) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `content` varchar(255) DEFAULT NULL,
  `series` int(11) DEFAULT NULL,
  `link` varchar(255) DEFAULT NULL,
  `member` int(33) DEFAULT NULL,
  `date` datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of forumlar
-- ----------------------------
INSERT INTO `forumlar` VALUES ('1', 'denemek-gerek', 'g', '1', 'denemek-gerek', '1', '2016-01-18 11:27:52');
INSERT INTO `forumlar` VALUES ('2', 'arkadaşım eşek', 'arkadaşım eş arkadaşım şek arkadaşm eşek', '2', 'arkadasim-esek', '2', '2016-01-11 23:52:31');`

**Comment by mertgonul** [comment]
tüm veritabanını dump edip verebilirmisin daha sorunsuz olur öyle.

**Comment by EmreTimur** [comment]
Merhaba, Muhammet bey iletişim için adreslernizi alabilir miyim ? Skype, Facebook gibi.

**Comment by mdxyz** [comment]
e-posta adresimi verebilirim: magicslip@gmail.com

**Comment by EmreTimur** [comment]
İletişim kuruldu ilginiz için teşekkürler.
