### ISSUE TITLE
Hatalar sorunsalı

### ISSUE THREAD

**Issue by mesutdincericoz** [mdxyz/dizilab#9]
www.hddizimag.com php surumu 5.6 olmasına ragmen bu hataları alıyorum
Notice: Undefined variable: view_folder in /home/dizimag/public_html/index.php on line 256

Warning: include(/home/dizimag/public_html/app/errors/error_php.php): failed to open stream: No such file or directory in /home/dizimag/public_html/system/core/Exceptions.php on line 183

Warning: include(): Failed opening '/home/dizimag/public_html/app/errors/error_php.php' for inclusion (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/dizimag/public_html/system/core/Exceptions.php on line 183

Warning: include(/home/dizimag/public_html/app/errors/error_php.php): failed to open stream: No such file or directory in /home/dizimag/public_html/system/core/Exceptions.php on line 183

Warning: include(): Failed opening '/home/dizimag/public_html/app/errors/error_php.php' for inclusion (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/dizimag/public_html/system/core/Exceptions.php on line 183

Warning: include(/home/dizimag/public_html/app/errors/error_php.php): failed to open stream: No such file or directory in /home/dizimag/public_html/system/core/Exceptions.php on line 183

Warning: include(): Failed opening '/home/dizimag/public_html/app/errors/error_php.php' for inclusion (include_path='.:/usr/lib/php:/usr/local/lib/php') in /home/dizimag/public_html/system/core/Exceptions.php on line 183
heryer eksıksız duzenledıgım halde.

**Comment by algoritmafakiri** [comment]
Doğrudur. Birkaç kişiden bu konu hakkında geribildirim aldım.
CodeIgniter sisteminde sorun var. Bilgisayarımda localhost üzerinden
sorunsuz erişim sağlayabiliyorum. Sadece ben değil birkaç arkadaşıma
da localhost üzerine kurdum ve sorunsuz çalıştı. dizilab scripti için
baştan sistem yazmayı düşünüyorum. İş güç musait olamıyorum. GitHub
üzerinden takipte kalın.

Saygılarımla

2016-03-24 2:58 GMT+02:00, mesutdincericoz <notifications@github.com>:

**Comment by mdxyz** [comment]
Doğrudur. Birkaç kişiden bu konu hakkında geribildirim aldım.
CodeIgniter sisteminde sorun var. Bilgisayarımda localhost üzerinden
sorunsuz erişim sağlayabiliyorum. Sadece ben değil birkaç arkadaşıma
da localhost üzerine kurdum ve sorunsuz çalıştı. dizilab scripti için
baştan sistem yazmayı düşünüyorum. İş güç musait olamıyorum. GitHub
üzerinden takipte kalın.

Saygılarımla

**Comment by mdxyz** [comment]
Doğrudur. Birkaç kişiden bu konu hakkında geribildirim aldım.
CodeIgniter sisteminde sorun var. Bilgisayarımda localhost üzerinden
sorunsuz erişim sağlayabiliyorum. Sadece ben değil birkaç arkadaşıma
da localhost üzerine kurdum ve sorunsuz çalıştı. dizilab scripti için
baştan sistem yazmayı düşünüyorum. İş güç musait olamıyorum. Takipte kalın.

Saygılarımla

**Comment by mesutdincericoz** [comment]
İletişim adresinizi alabilir miyim mail attım ulaşamadım.

**Comment by mdxyz** [comment]
Bu sorunu index.php dosyasına
`$view_folder = null;`
ekleyerek çözebilirsiniz.
Sadece bu sorun hakkında değil, birkaç sorun hakkında birkaç kişiden geribildirim aldım.
CodeIgniter sisteminde sorun var. Bilgisayarımda localhost üzerinden
sorunsuz erişim sağlayabiliyorum. Sadece ben değil birkaç arkadaşıma
da localhost üzerine kurdum ve sorunsuz çalıştı. dizilab scripti için
baştan sistem yazmayı düşünüyorum. İş güç musait olamıyorum. Takipte kalın.

Saygılarımla

**Comment by mesutdincericoz** [comment]
ana dizindeki index.php <?php bir alt satırına ekledım en son eklediğinizi fakat değişen birşey yok php sürümü 5.6 sizden geçicide olsa bu konuda yardım rica ediyorum.

**Comment by mdxyz** [comment]
`$application_folder = 'app';` satırının altına ekleyin.

Saygılarımla

**Comment by mesutdincericoz** [comment]
Teşekkürler fakat ekledim halde gene aynı hata. www.hddizimag.com ftp verebilirim dilersen mailden yazdım oradan dönmedin henüz.

**Comment by mdxyz** [comment]
Görüldüğü üzere _view_folder_ sorunu çözülmüş. Diğer sorun üstte yazdığım 
> Sadece bu sorun hakkında değil, birkaç sorun hakkında birkaç kişiden geribildirim aldım.

Şu anlık çözümü ise scripti başka sistem üzerine yazmak. Bu süre zarfında CodeIgniter geliştiricileri sorun hakkında düzenleme getirirse scripti güncelleyeceğim.

Saygılarımla

**Comment by mesutdincericoz** [comment]
Anladım mailden ulaştım rica etsem bakabilir misin hem öneri hemde güzel bir konu hakkında.

**Comment by EmreTimur** [comment]
app/errors/error_php.php oluşturun sorun ortadan kalkacaktır.

**Comment by mesutdincericoz** [comment]
Zaten öyle bir dosya var.

**Comment by EmreTimur** [comment]
Hostunuz kaynaklı bir sorun vardır eror_php.php olduğundan emin olunuz. Çünkü bizler kurulumu gerçekleştirebildik local'de.

**Comment by mesutdincericoz** [comment]
localde sorun yokmus zaten sorun codeıgnıterdeymıs bana localdekı halının goruntulerını atabılır mısın cok merak edıyorum takipkusuorg@gmail.com

**Comment by EmreTimur** [comment]
İnternet üzerinde bir çok demosu bulunmaktadır.

**Comment by mesutdincericoz** [comment]
Arkadaşın paylaştığı tema ne halde onu görmek istedim.

**Comment by EmreTimur** [comment]
İnternet üzerinde bir çok demosu bulunmaktadır. Clone ne demek aynısı demek fark yok.

**Comment by mdxyz** [comment]
Sorunlar giderilip, website üzerinde denendi. Çözüldü.
